piVersion: apps/v1

kind: Deployment

metadata:

  name: sample-1

  labels:

    app: sample-1

spec:

  replicas: 1

  selector:

    matchLabels:

      app: sample-1

  template:

    metadata:

      labels:

        app: sample-1

    spec:

      containers:

      - name: sample-1

        image: devopsprosamples/next-path-sample-1